version: '3'

services:
  server-glushko:
    image: 'messengertgnk-backend'
    build:
      context: ./backend
    container_name: backend-glushko
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-glushko:5432/messenger
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=251323Nn
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "9992:8080"

  client-glushko:
    image: 'messengertgnk-frontend'
    build:
      context: ./frontend
    container_name: front-glushko
    stdin_open: true
    restart: always
    ports:
      - "1002:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://45.94.116.38:9992

  postgres-glushko:
    container_name: postgres-glushko
    image: 'postgres:14'
    environment:
      - POSTGRES_DB=messenger
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=251323Nn
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/src/main/resources/sql:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

    restart: unless-stopped

volumes:
  postgres-data: